name: asif
on:
    pull_request: 
      branches: 
      - 'main'
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
        - name: step1
          run: echo "${{ github.head.ref }}"
        - run: echo "${{ github.base.ref }}"
        - run: echo "${{ secrets.DEMO123 }}"
        - run: echo added something